name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

#      - name: Run tests
 #       run: dotnet test --filter "FullyQualifiedName~MapperIA.Tests.Mappers.ClassMapper.ClassMapperTests | FullyQualifiedName~MapperIA.Tests.Mappers.PDFMapper.PDFMapperTests"


      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push **/bin/Release/*.nupkg --api-key $GITHUB_TOKEN --source https://nuget.pkg.github.com/01Dri/index.json"

