name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

#     - name: Run tests
#       run: dotnet test

      - name: Add GitHub NuGet source
        run: dotnet nuget add source "https://nuget.pkg.github.com/01Dri/index.json" --name "github" --username "01Dri" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

      - name: Publish to GitHub Packages (NuGet)
        run: dotnet nuget push **/bin/Release/*.nupkg --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}"
